import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  HomePage({super.key});

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  // Track which category is currently expanded
  int? expandedCategoryIndex;

  // Categories and their unique, strongest features
  final List<Map<String, dynamic>> categories = [
    {
      'title': 'Resume Building Tools',
      'icon': Icons.build,
      'features': [
        {
          'title': 'Resume Tailoring with AI',
          'route': '/resumeTailoring',
          'icon': Icons.tune,
          'description':
              'Use AI to tailor your resume to specific job descriptions.',
        },
        {
          'title': 'Build Resume',
          'route': '/personalInfo',
          'icon': Icons.edit,
          'description':
              'Start building your resume with personal information.',
        },
        {
          'title': 'AI Resume & Cover Letter Generator',
          'route': '/resumeGenerator',
          'icon': Icons.description,
          'description': 'Generate resumes and cover letters using AI.',
        },
        {
          'title': 'Portfolio Builder',
          'route': '/portfolioBuilder',
          'icon': Icons.folder_special,
          'description': 'Create portfolios for creative fields.',
        },
        {
          'title': 'Skill-Based Resumes & Learning Suggestions',
          'route': '/skillBasedResumes',
          'icon': Icons.list_alt,
          'description':
              'Create skill-focused resumes and get learning suggestions.',
        },
      ],
    },
    {
      'title': 'Job Application Management',
      'icon': Icons.work,
      'features': [
        {
          'title': 'Application Tracker Dashboard',
          'route': '/applicationTracker',
          'icon': Icons.track_changes,
          'description': 'Manage and track your job applications.',
        },
        {
          'title': 'Job Market Trends & Salary Estimation',
          'route': '/marketTrends',
          'icon': Icons.trending_up,
          'description': 'View job market trends and estimate salaries.',
        },
      ],
    },
    {
      'title': 'Career Development Tools',
      'icon': Icons.school,
      'features': [
        {
          'title': 'Interview Preparation with AI',
          'route': '/interviewPrep',
          'icon': Icons.question_answer,
          'description': 'Practice interview questions generated by AI.',
        },
      ],
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            const Text('Home'),
            const SizedBox(width: 16),
            Expanded(
              child: SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: List.generate(categories.length, (index) {
                    final category = categories[index];
                    return GestureDetector(
                      onTap: () {
                        setState(() {
                          if (expandedCategoryIndex == index) {
                            // Collapse if already expanded
                            expandedCategoryIndex = null;
                          } else {
                            // Expand the selected category
                            expandedCategoryIndex = index;
                          }
                        });
                      },
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12.0, vertical: 8.0),
                        margin: const EdgeInsets.symmetric(horizontal: 4.0),
                        decoration: BoxDecoration(
                          color: expandedCategoryIndex == index
                              ? Colors.blue[700]
                              : Colors.blueAccent,
                          borderRadius: BorderRadius.circular(8.0),
                        ),
                        child: Row(
                          children: [
                            Icon(category['icon'],
                                color: Colors.white, size: 24),
                            const SizedBox(width: 8),
                            Text(
                              category['title'],
                              style: const TextStyle(
                                  fontSize: 16, color: Colors.white),
                            ),
                          ],
                        ),
                      ),
                    );
                  }),
                ),
              ),
            ),
          ],
        ),
        backgroundColor: Colors.blueAccent,
      ),
      body: Stack(
        children: [
          // Main Content
          Positioned.fill(
            child: SingleChildScrollView(
              child: Column(
                children: [
                  const SizedBox(height: 20),
                  // Additional content
                  Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: const Text(
                      'Welcome to the Career Enhancement Platform!',
                      style:
                          TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                      textAlign: TextAlign.center,
                    ),
                  ),
                  // Add more content here if needed
                ],
              ),
            ),
          ),
          // Subcategories Dropdown
          if (expandedCategoryIndex != null)
            Positioned(
              top: kToolbarHeight, // Positions the submenu below the AppBar
              left: 0,
              right: 0,
              child: Container(
                color: Colors.blue[100],
                constraints: BoxConstraints(
                  maxHeight:
                      MediaQuery.of(context).size.height - kToolbarHeight,
                ),
                child: SingleChildScrollView(
                  child: Column(
                    children: categories[expandedCategoryIndex!]['features']
                        .map<Widget>((feature) {
                      return ListTile(
                        leading:
                            Icon(feature['icon'], color: Colors.blueAccent),
                        title: Text(feature['title']),
                        subtitle: Text(feature['description']),
                        onTap: () {
                          Navigator.pushNamed(context, feature['route']);
                          // Collapse the submenu after navigation
                          setState(() {
                            expandedCategoryIndex = null;
                          });
                        },
                      );
                    }).toList(),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}
