import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {
  HomePage({super.key});

  // Categories and their unique, strongest features
  final List<Map<String, dynamic>> categories = [
    {
      'title': 'Resume Building Tools',
      'icon': Icons.build,
      'features': [
        {
          'title': 'Resume Tailoring with AI',
          'route': '/resumeTailoring',
          'icon': Icons.tune,
          'description':
              'Use AI to tailor your resume to specific job descriptions.',
        },
        {
          'title':
              'Build Resume', // Updated Resume flow to start with Personal Info
          'route': '/personalInfo', // Navigate to personal info first
          'icon': Icons.edit,
          'description':
              'Start building your resume with personal information.',
        },
        {
          'title': 'AI Resume & Cover Letter Generator',
          'route': '/resumeGenerator',
          'icon': Icons.description,
          'description': 'Generate resumes and cover letters using AI.',
        },
        {
          'title': 'Portfolio Builder',
          'route': '/portfolioBuilder',
          'icon': Icons.folder_special,
          'description': 'Create portfolios for creative fields.',
        },
        {
          'title': 'Skill-Based Resumes & Learning Suggestions',
          'route': '/skillBasedResumes',
          'icon': Icons.list_alt,
          'description':
              'Create skill-focused resumes and get learning suggestions.',
        },
      ],
    },
    {
      'title': 'Job Application Management',
      'icon': Icons.work,
      'features': [
        {
          'title': 'Application Tracker Dashboard',
          'route': '/applicationTracker',
          'icon': Icons.track_changes,
          'description': 'Manage and track your job applications.',
        },
        {
          'title': 'Job Market Trends & Salary Estimation',
          'route': '/marketTrends',
          'icon': Icons.trending_up,
          'description': 'View job market trends and estimate salaries.',
        },
      ],
    },
    {
      'title': 'Career Development Tools',
      'icon': Icons.school,
      'features': [
        {
          'title': 'Interview Preparation with AI',
          'route': '/interviewPrep',
          'icon': Icons.question_answer,
          'description': 'Practice interview questions generated by AI.',
        },
      ],
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
        backgroundColor: Colors.blueAccent,
      ),
      body: ListView(
        children: [
          // Generate ExpansionTiles for each category
          ...categories.map((category) {
            return ExpansionTile(
              leading: Icon(category['icon'], color: Colors.blueAccent),
              title: Text(
                category['title'],
                style:
                    const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              children: category['features'].map<Widget>((feature) {
                return ListTile(
                  leading: Icon(feature['icon'], color: Colors.blueAccent),
                  title: Text(feature['title']),
                  subtitle: Text(feature['description']),
                  onTap: () {
                    Navigator.pushNamed(context, feature['route']);
                  },
                );
              }).toList(),
            );
          }).toList(),
          // Additional content
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: const Text(
              'Welcome to the Career Enhancement Platform!',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              textAlign: TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }
}
